### ISSUE TITLE
Inquiry about model and data

### ISSUE THREAD

**Issue by xiaoxin-yin** [felix-lyx/prose#2]
Hi @felix-lyx and @JingminSun ,

It is great to see your work on symbolic regression on differential equations, and I hope to try it out. Could you share the model and data for it?

Thank you!
Xiaoxin

**Comment by JingminSun** [comment]
Dear @xiaoxin-yin,

Sorry for late reply.
I've uploaded a data generation script for prose_pde, it is under prose_pde/scripts folder. Please check that out.
If you are interested in pde work, you can also check out another repo of our group: https://github.com/JingminSun/prose_v1, which include an updated model.

Best
Jingmin

**Comment by xiaoxin-yin** [comment]
Thank you, Jingmin!
